In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
file_path = "./Resources/Student_performance_data _.csv"
df = pd.read_csv(file_path)

In [3]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [5]:
df.describe().round(0)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0,2392.0
mean,2196.0,16.0,1.0,1.0,2.0,10.0,15.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,3.0
std,691.0,1.0,0.0,1.0,1.0,6.0,8.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
min,1001.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1599.0,15.0,0.0,0.0,1.0,5.0,7.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0
50%,2196.0,16.0,1.0,0.0,2.0,10.0,15.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,4.0
75%,2794.0,17.0,1.0,2.0,2.0,14.0,22.0,1.0,3.0,1.0,1.0,0.0,0.0,3.0,4.0
max,3392.0,18.0,1.0,3.0,4.0,20.0,29.0,1.0,4.0,1.0,1.0,1.0,1.0,4.0,4.0

In [6]:
# Compute the correlation matrix
corr_matrix = df.corr()

print("Correlation Matrix:")
print(corr_matrix)

Correlation Matrix:
                   StudentID       Age    Gender  Ethnicity  \
StudentID           1.000000 -0.042255 -0.014625  -0.012990
Age                -0.042255  1.000000  0.044895  -0.028473
Gender             -0.014625  0.044895  1.000000   0.016010
Ethnicity          -0.012990 -0.028473  0.016010   1.000000
ParentalEducation  -0.002307  0.025099  0.006771   0.033595
StudyTimeWeekly     0.026976 -0.006800  0.011469   0.007184
Absences            0.014841 -0.011511  0.021479  -0.025712
Tutoring           -0.007834 -0.012076 -0.031597  -0.017440
ParentalSupport     0.003016  0.033197  0.008065   0.020922
Extracurricular    -0.003611 -0.025061 -0.005964  -0.008927
Sports             -0.020703 -0.046320 -0.008897  -0.004484
Music              -0.005468 -0.003492  0.007109  -0.014627
Volunteering        0.008011  0.013074 -0.000200   0.013468
GPA                -0.002697  0.000275 -0.013360   0.027760
GradeClass         -0.098500 -0.006250  0.022998  -0.023326

                   ParentalEducation  StudyTimeWeekly  Absences  Tutoring  \
StudentID                  -0.002307         0.026976  0.014841 -0.007834
Age                         0.025099        -0.006800 -0.011511 -0.012076
Gender                      0.006771         0.011469  0.021479 -0.031597
Ethnicity                   0.033595         0.007184 -0.025712 -0.017440
ParentalEducation           1.000000        -0.011051  0.036518 -0.017340
StudyTimeWeekly            -0.011051         1.000000  0.009326  0.028930
Absences                    0.036518         0.009326  1.000000 -0.015534
Tutoring                   -0.017340         0.028930 -0.015534  1.000000
ParentalSupport            -0.017463         0.035800  0.002108 -0.000824
Extracurricular             0.007479        -0.022860  0.000360  0.004865
Sports                      0.002029         0.006836  0.041454  0.006278
Music                       0.039439         0.007791 -0.008692 -0.011385
Volunteering                0.011960        -0.016604 -0.018528 -0.050898
GPA                        -0.035854         0.179275 -0.919314  0.145119
GradeClass                  0.041031        -0.134131  0.728633 -0.111695

                   ParentalSupport  Extracurricular    Sports     Music  \
StudentID                 0.003016        -0.003611 -0.020703 -0.005468
Age                       0.033197        -0.025061 -0.046320 -0.003492
Gender                    0.008065        -0.005964 -0.008897  0.007109
Ethnicity                 0.020922        -0.008927 -0.004484 -0.014627
ParentalEducation        -0.017463         0.007479  0.002029  0.039439
StudyTimeWeekly           0.035800        -0.022860  0.006836  0.007791
Absences                  0.002108         0.000360  0.041454 -0.008692
Tutoring                 -0.000824         0.004865  0.006278 -0.011385
ParentalSupport           1.000000        -0.008381 -0.006176  0.035122
Extracurricular          -0.008381         1.000000 -0.011820 -0.014191
Sports                   -0.006176        -0.011820  1.000000 -0.020474
Music                     0.035122        -0.014191 -0.020474  1.000000
Volunteering             -0.006036        -0.007427 -0.002799  0.017224
GPA                       0.190774         0.094078  0.057859  0.073318
GradeClass               -0.136823        -0.069733 -0.026654 -0.036065

                   Volunteering       GPA  GradeClass
StudentID              0.008011 -0.002697   -0.098500
Age                    0.013074  0.000275   -0.006250
Gender                -0.000200 -0.013360    0.022998
Ethnicity              0.013468  0.027760   -0.023326
ParentalEducation      0.011960 -0.035854    0.041031
StudyTimeWeekly       -0.016604  0.179275   -0.134131
Absences              -0.018528 -0.919314    0.728633
Tutoring              -0.050898  0.145119   -0.111695
ParentalSupport       -0.006036  0.190774   -0.136823
Extracurricular       -0.007427  0.094078   -0.069733
Sports                -0.002799  0.057859   -0.026654
Music                  0.017224  0.073318   -0.036065
Volunteering           1.000000  0.003258    0.013156
GPA                    0.003258  1.000000   -0.782835
GradeClass             0.013156 -0.782835    1.000000